# Generated by Django 3.0.6 on 2020-07-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='type',
            field=models.IntegerField(choices=[(1, 'BLR'), (2, 'RUB'), (3, 'UAH'), (4, 'PLN'), (5, 'USD'), (6, 'EUR')]),
        ),
    ]
