# Generated by Django 3.0.6 on 2020-08-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_auto_20200726_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='text',
            field=models.CharField(max_length=50),
        ),
    ]
