# Generated by Django 3.0.6 on 2020-08-02 13:14

from django.db import migrations, models
import records.models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_auto_20200802_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('count', models.CharField(max_length=10)),
                ('value', models.FloatField(validators=[records.models.validate_positive])),
            ],
        ),
    ]
