# Generated by Django 3.0.6 on 2020-08-08 00:01

from django.db import migrations, models
import records.models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='value_in_blr',
            field=models.FloatField(default=100, validators=[records.models.validate_positive]),
            preserve_default=False,
        ),
    ]
