# Generated by Django 3.0.6 on 2020-08-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_record_value_in_blr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
