# Generated by Django 3.0.6 on 2020-08-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_auto_20200826_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenserecord',
            name='text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='incomerecord',
            name='text',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
