# Generated by Django 3.0.6 on 2020-10-23 18:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_auto_20201023_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='days',
        ),
        migrations.AddField(
            model_name='budget',
            name='finish_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
